-- MySQL Script generated by MySQL Workbench
-- Sun Apr 13 00:54:41 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BDWAYNE
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BDWAYNE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BDWAYNE` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `BDWAYNE` ;

-- -----------------------------------------------------
-- Table `BDWAYNE`.`equipamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDWAYNE`.`equipamentos` (
  `id_patrimonio` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(40) NOT NULL,
  `marca` VARCHAR(30) NOT NULL,
  `modelo` VARCHAR(30) NOT NULL,
  `serie` VARCHAR(20) NULL DEFAULT NULL,
  `imei` VARCHAR(20) NULL DEFAULT NULL,
  `data_compra` DATE NULL DEFAULT NULL,
  `fornecedor` VARCHAR(30) NULL DEFAULT NULL,
  `valor_compra` DECIMAL(10,0) NOT NULL,
  `documento_fiscal_compra` VARCHAR(10) NULL DEFAULT NULL,
  `data_venda` DATE NULL DEFAULT NULL,
  `comprador` VARCHAR(30) NULL DEFAULT NULL,
  `valor_venda` DECIMAL(10,0) NULL DEFAULT NULL,
  `documento_fiscal_venda` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id_patrimonio`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BDWAYNE`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDWAYNE`.`funcionarios` (
  `id_matricula` INT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(30) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `rg` VARCHAR(11) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `data_admissao` DATE NOT NULL,
  `cargo` VARCHAR(30) NOT NULL,
  `email_corporativo` VARCHAR(30) NOT NULL,
  `telefone_corporativo` VARCHAR(11) NOT NULL,
  `data_demissao` DATE NULL DEFAULT ((1900 - 1) - 1),
  PRIMARY KEY (`id_matricula`),
  UNIQUE INDEX `cpf` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `email_corporativo` (`email_corporativo` ASC) VISIBLE,
  UNIQUE INDEX `email_corporativo_2` (`email_corporativo` ASC) VISIBLE,
  UNIQUE INDEX `email_corporativo_3` (`email_corporativo` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BDWAYNE`.`controle_equipamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDWAYNE`.`controle_equipamentos` (
  `id_contr_equipamento` INT NOT NULL AUTO_INCREMENT,
  `id_patrimonio` INT NOT NULL,
  `id_matricula` INT NOT NULL,
  `setor` VARCHAR(30) NULL DEFAULT NULL,
  `data_registro` DATE NOT NULL,
  `motivo` VARCHAR(15) NULL DEFAULT NULL,
  `observacao` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id_contr_equipamento`),
  INDEX `id_patrimonio` (`id_patrimonio` ASC) VISIBLE,
  INDEX `id_matricula` (`id_matricula` ASC) VISIBLE,
  CONSTRAINT `controle_equipamentos_ibfk_1`
    FOREIGN KEY (`id_patrimonio`)
    REFERENCES `BDWAYNE`.`equipamentos` (`id_patrimonio`),
  CONSTRAINT `controle_equipamentos_ibfk_2`
    FOREIGN KEY (`id_matricula`)
    REFERENCES `BDWAYNE`.`funcionarios` (`id_matricula`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BDWAYNE`.`veiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDWAYNE`.`veiculos` (
  `id_registro` INT NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(7) NOT NULL,
  `marca` VARCHAR(30) NOT NULL,
  `modelo` VARCHAR(30) NOT NULL,
  `ano` VARCHAR(4) NOT NULL,
  `chassi` VARCHAR(17) NOT NULL,
  `renavam` VARCHAR(11) NOT NULL,
  `data_compra` DATE NOT NULL,
  `fornecedor` VARCHAR(30) NOT NULL,
  `valor_compra` VARCHAR(10) NOT NULL,
  `documento_fiscal_compra` VARCHAR(10) NOT NULL,
  `data_venda` DATE NULL DEFAULT ((1900 - 1) - 1),
  `comprador` VARCHAR(30) NULL DEFAULT NULL,
  `valor_venda` VARCHAR(10) NULL DEFAULT NULL,
  `documento_fiscal_venda` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id_registro`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BDWAYNE`.`controle_veiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDWAYNE`.`controle_veiculos` (
  `id_contr_veiculos` INT NOT NULL AUTO_INCREMENT,
  `id_registro` INT NOT NULL,
  `id_matricula` INT NOT NULL,
  `data_hora_saida` DATETIME NULL DEFAULT NULL,
  `data_hora_entrada` DATETIME NULL DEFAULT NULL,
  `enviar_para_entrada` VARCHAR(10) NULL DEFAULT NULL,
  `motivo` VARCHAR(500) NULL DEFAULT NULL,
  `observacao_entrada` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id_contr_veiculos`),
  INDEX `id_registro` (`id_registro` ASC) VISIBLE,
  INDEX `id_matricula` (`id_matricula` ASC) VISIBLE,
  CONSTRAINT `controle_veiculos_ibfk_1`
    FOREIGN KEY (`id_registro`)
    REFERENCES `BDWAYNE`.`veiculos` (`id_registro`),
  CONSTRAINT `controle_veiculos_ibfk_2`
    FOREIGN KEY (`id_matricula`)
    REFERENCES `BDWAYNE`.`funcionarios` (`id_matricula`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BDWAYNE`.`suporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDWAYNE`.`suporte` (
  `id_suporte` INT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `problema` TEXT NULL DEFAULT NULL,
  `data_solicitacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_suporte`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BDWAYNE`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDWAYNE`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `id_matricula` INT NOT NULL,
  `usuario` VARCHAR(20) NULL DEFAULT NULL,
  `senha` VARCHAR(50) NULL DEFAULT NULL,
  `data_criacao_senha` DATE NULL DEFAULT NULL,
  `data_alteracao_senha` DATE NULL DEFAULT NULL,
  `primeiro_acesso` TINYINT(1) NULL DEFAULT '1',
  PRIMARY KEY (`id_usuario`),
  INDEX `id_matricula` (`id_matricula` ASC) VISIBLE,
  CONSTRAINT `usuarios_ibfk_1`
    FOREIGN KEY (`id_matricula`)
    REFERENCES `BDWAYNE`.`funcionarios` (`id_matricula`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
